#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Mar 13 10:57:35 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto be13fdd9cc774d8083944a157f058275 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L gtwizard_ultrascale_v1_7_7 -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_scout_behav xil_defaultlib.tb_scout xil_defaultlib.glbl -log elaborate.log"
xelab -wto be13fdd9cc774d8083944a157f058275 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L gtwizard_ultrascale_v1_7_7 -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_scout_behav xil_defaultlib.tb_scout xil_defaultlib.glbl -log elaborate.log

