# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8.xci
# IP: The module: 'pcie3_uscale_plus_x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/pcie3_uscale_plus_x8_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie3_uscale_plus_x8_gt || ORIG_REF_NAME==pcie3_uscale_plus_x8_gt} -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt_ooc.xdc

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie3_uscale_plus_x8_gt || ORIG_REF_NAME==pcie3_uscale_plus_x8_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/source/ip_pcie4_uscale_plus_x1y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8.xci
# IP: The module: 'pcie3_uscale_plus_x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/pcie3_uscale_plus_x8_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie3_uscale_plus_x8_gt || ORIG_REF_NAME==pcie3_uscale_plus_x8_gt} -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt_ooc.xdc

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie3_uscale_plus_x8_gt || ORIG_REF_NAME==pcie3_uscale_plus_x8_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/source/ip_pcie4_uscale_plus_x1y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie3_uscale_plus_x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
