# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
# IP: The module: 'fifo_generator_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
# IP: The module: 'fifo_generator_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
