# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/SB852_VU9P_FLVB2104_E.xdc

# TCL: imports/src/clocks.tcl

# XDC: imports/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc

# XDC: imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc

# XDC: imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc

# IP: ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtwizard_ultrascale_0_vio_0 || ORIG_REF_NAME==gtwizard_ultrascale_0_vio_0} -quiet] -quiet
