# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu9p-flgb2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.cache/wt [current_project]
set_property parent.project_path /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0/gtwizard_ultrascale_0.dcp
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0/gtwizard_ultrascale_0.dcp]
read_verilog {
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/BasePicoDefines.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/PicoDefines.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/functions.vh
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/axi_defines.v
}
set_property file_type "Verilog Header" [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/BasePicoDefines.v]
set_property file_type "Verilog Header" [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/PicoDefines.v]
set_property file_type "Verilog Header" [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/axi_defines.v]
read_verilog -library xil_defaultlib -sv {
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/UserWrapper.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/Pico_Toplevel.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/PicoInterfaces.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/UtilFunc.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/axilite_to_picobus.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/xilinx/src/XilinxInterfaces.sv
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/async_data_mmrs_axi_interface.sv
}
read_verilog -library xil_defaultlib {
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/CardInfo32.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/CounterClkGen.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PCIeHdrAlignSplit.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PIO_128_RX_ENGINE.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PIO_128_TX_ENGINE.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PIO_EP.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PIO_Reorder.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoFramework.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoStreamIn.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoStreamOut.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/Stream2PicoBus.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/flash/StreamToFlashCtl.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/StreamToPicoBus.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/StreamWidthConversion.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/SystemMonitor32.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/TagFIFO.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/TestCounter32.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/count_updater.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/dpram.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/fsync.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/generic_fifo.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_bit_sync.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_checking_8b10b.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_rx.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_gtwiz_userclk_tx.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_init.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_reset_sync.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_stimulus_8b10b.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_top.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gt_ultrascale_custom_top.v
  /home/tjames/StreamLoopback128/firmware/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_wrapper.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_prbs_any.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0/gtwizard_ultrascale_0_stub.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0_stub.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/flash/i2c_master.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/flash/mgmt_qspi_flash_ctl.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/xilinx/src/pcie3_7x_to_v1_6.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/pcie_app_v6.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/flash/sdpram.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/sync1.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/sync2r.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/xilinx/src/xilinx_pcie_3_0_7vx.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_bit_sync.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_checking_8b10b.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_init.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_reset_sync.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_stimulus_8b10b.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_wrapper.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/StreamLoopback128.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/AXIToHMC.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/AXIToHMCWrapper.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/sync2.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/HMCReorder.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/HMCTagManager.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/Reorder.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoAXIDownsizer.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoAXIUpsizer.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoStreamToAXI.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/PicoStreamToHMC.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/StreamAXICtrl.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/RGBBlink.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/fifo_512x128.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/src/pcie_axi/asyncFifoBRAM.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/firmware/SB852_VU9P_StreamLoopback128/firmware/xilinx/src/FIFO.v
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/imports/gtwizard_ultrascale_0_example_top_sim.v
}
read_vhdl -library work {
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/datatypes.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/gap_cleaner.vhd
}
read_vhdl -library xil_defaultlib {
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/auto_realign_controller.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/freq_meas.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/synchroniser.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/reset.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/aligner.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/fifo_filler.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/scout_inputs.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0_stub.vhdl
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0_sim_netlist.vhdl
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0/gtwizard_ultrascale_0_sim_netlist.vhdl
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/gtwizard_ultrascale_0/gtwizard_ultrascale_0_stub.vhdl
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/zero_suppression.vhd
  /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/new/scout_top.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/imports/new/test_file_io.vhd
read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0_vio_0/gtwizard_ultrascale_0_vio_0_ooc.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/ip_0/synth/pcie3_uscale_plus_x8_gt.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/pcie3_uscale_plus_x8_board.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/synth/pcie3_uscale_plus_x8_late.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/pcie3_uscale_plus_x8/source/ip_pcie4_uscale_plus_x1y2.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/aligner_fifo/aligner_fifo.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/aligner_fifo/aligner_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/aligner_fifo/aligner_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/aligner_fifo/aligner_fifo_ooc.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc]
set_property used_in_implementation false [get_files -all /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/src/SB852_VU9P_FLVB2104_E.xdc
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/src/SB852_VU9P_FLVB2104_E.xdc]

read_xdc -unmanaged /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/src/clocks.tcl
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/src/clocks.tcl]

read_xdc /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/imports/gtwizard_ultrascale_0_example_top.xdc]

read_xdc /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc]

read_xdc /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc
set_property used_in_implementation false [get_files /home/tjames/StreamLoopback128/firmware/SB852_VU9P_StreamLoopback128/SB852_VU9P_StreamLoopback128.srcs/constrs_1/imports/gtwizard_ultrascale_0_ex/gtwizard_ultrascale_0_ex.srcs/sources_1/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Pico_Toplevel -part xcvu9p-flgb2104-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pico_Toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pico_Toplevel_utilization_synth.rpt -pb Pico_Toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
